#pragma once

#include <di/function/as_bool.h>
#include <di/function/bind_back.h>
#include <di/function/bind_front.h>
#include <di/function/bit_and.h>
#include <di/function/chain.h>
#include <di/function/compare.h>
#include <di/function/compare_backwards.h>
#include <di/function/compose.h>
#include <di/function/container/prelude.h>
#include <di/function/curry.h>
#include <di/function/curry_back.h>
#include <di/function/dereference.h>
#include <di/function/equal.h>
#include <di/function/equal_or_greater.h>
#include <di/function/equal_or_less.h>
#include <di/function/flip.h>
#include <di/function/generator.h>
#include <di/function/greater.h>
#include <di/function/identity.h>
#include <di/function/into_void.h>
#include <di/function/invoke.h>
#include <di/function/less.h>
#include <di/function/minus.h>
#include <di/function/monad/prelude.h>
#include <di/function/multiplies.h>
#include <di/function/not_equal.h>
#include <di/function/not_fn.h>
#include <di/function/overload.h>
#include <di/function/piped.h>
#include <di/function/pipeline.h>
#include <di/function/plus.h>
#include <di/function/tag_invoke.h>
#include <di/function/uncurry.h>
#include <di/function/value.h>
#include <di/function/ycombinator.h>
