#pragma once

#include <di/container/algorithm/all_of.h>
#include <di/container/algorithm/any_of.h>
#include <di/container/algorithm/clamp.h>
#include <di/container/algorithm/compare.h>
#include <di/container/algorithm/contains.h>
#include <di/container/algorithm/contains_subrange.h>
#include <di/container/algorithm/count.h>
#include <di/container/algorithm/count_if.h>
#include <di/container/algorithm/ends_with.h>
#include <di/container/algorithm/equal.h>
#include <di/container/algorithm/find.h>
#include <di/container/algorithm/find_if.h>
#include <di/container/algorithm/find_if_not.h>
#include <di/container/algorithm/fold_left.h>
#include <di/container/algorithm/for_each.h>
#include <di/container/algorithm/is_sorted.h>
#include <di/container/algorithm/is_sorted_until.h>
#include <di/container/algorithm/max.h>
#include <di/container/algorithm/max_element.h>
#include <di/container/algorithm/min.h>
#include <di/container/algorithm/min_element.h>
#include <di/container/algorithm/mismatch.h>
#include <di/container/algorithm/none_of.h>
#include <di/container/algorithm/reverse.h>
#include <di/container/algorithm/rotate.h>
#include <di/container/algorithm/search.h>
#include <di/container/algorithm/starts_with.h>
#include <di/container/algorithm/sum.h>

namespace di {
using container::all_of;
using container::any_of;
using container::clamp;
using container::contains;
using container::contains_subrange;
using container::count;
using container::count_if;
using container::ends_with;
using container::find;
using container::find_if;
using container::find_if_not;
using container::fold_left;
using container::for_each;
using container::is_sorted;
using container::is_sorted_until;
using container::max;
using container::max_element;
using container::min;
using container::min_element;
using container::mismatch;
using container::none_of;
using container::rotate;
using container::search;
using container::starts_with;
using container::sum;
}
