coverage:
    ignore:
        - "**/tests"
    status:
        project:
            default:
                informational: true
        patch:
            default:
                informational: true
