var io__uring__context_8h =
[
    [ "dius::linux::OperationStateBase", "structdius_1_1linux_1_1OperationStateBase.html", "structdius_1_1linux_1_1OperationStateBase" ],
    [ "dius::linux::IoUringContext", "structdius_1_1linux_1_1IoUringContext.html", "structdius_1_1linux_1_1IoUringContext" ],
    [ "dius::linux::IoUringScheduler", "structdius_1_1linux_1_1IoUringScheduler.html", "structdius_1_1linux_1_1IoUringScheduler" ],
    [ "dius::linux::Env", "structdius_1_1linux_1_1Env.html", "structdius_1_1linux_1_1Env" ],
    [ "dius::linux::ReadSomeSender", "structdius_1_1linux_1_1ReadSomeSender.html", "structdius_1_1linux_1_1ReadSomeSender" ],
    [ "dius::linux::ReadSomeSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1ReadSomeSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1ReadSomeSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::WriteSomeSender", "structdius_1_1linux_1_1WriteSomeSender.html", "structdius_1_1linux_1_1WriteSomeSender" ],
    [ "dius::linux::WriteSomeSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1WriteSomeSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1WriteSomeSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::CloseSender", "structdius_1_1linux_1_1CloseSender.html", "structdius_1_1linux_1_1CloseSender" ],
    [ "dius::linux::CloseSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1CloseSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1CloseSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::ConnectSender", "structdius_1_1linux_1_1ConnectSender.html", "structdius_1_1linux_1_1ConnectSender" ],
    [ "dius::linux::ConnectSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1ConnectSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1ConnectSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::BindSender", "structdius_1_1linux_1_1BindSender.html", "structdius_1_1linux_1_1BindSender" ],
    [ "dius::linux::BindSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1BindSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1BindSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::ListenSender", "structdius_1_1linux_1_1ListenSender.html", "structdius_1_1linux_1_1ListenSender" ],
    [ "dius::linux::ListenSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1ListenSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1ListenSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::ShutdownSender", "structdius_1_1linux_1_1ShutdownSender.html", "structdius_1_1linux_1_1ShutdownSender" ],
    [ "dius::linux::ShutdownSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1ShutdownSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1ShutdownSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::ScheduleSender", "structdius_1_1linux_1_1ScheduleSender.html", "structdius_1_1linux_1_1ScheduleSender" ],
    [ "dius::linux::ScheduleSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1ScheduleSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1ScheduleSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::AsyncFile", "classdius_1_1linux_1_1AsyncFile.html", "classdius_1_1linux_1_1AsyncFile" ],
    [ "dius::linux::AcceptSocket", "classdius_1_1linux_1_1AcceptSocket.html", "classdius_1_1linux_1_1AcceptSocket" ],
    [ "dius::linux::AsyncSocket< Base >", "classdius_1_1linux_1_1AsyncSocket.html", "classdius_1_1linux_1_1AsyncSocket" ],
    [ "dius::linux::OpenSender", "structdius_1_1linux_1_1OpenSender.html", "structdius_1_1linux_1_1OpenSender" ],
    [ "dius::linux::OpenSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1OpenSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1OpenSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::MakeSocketSender", "structdius_1_1linux_1_1MakeSocketSender.html", "structdius_1_1linux_1_1MakeSocketSender" ],
    [ "dius::linux::MakeSocketSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1MakeSocketSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1MakeSocketSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::AcceptSender", "structdius_1_1linux_1_1AcceptSender.html", "structdius_1_1linux_1_1AcceptSender" ],
    [ "dius::linux::AcceptSender::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1AcceptSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1AcceptSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::RunSender< Object, CreateSend >", "structdius_1_1linux_1_1RunSender.html", "structdius_1_1linux_1_1RunSender" ],
    [ "dius::linux::RunSender< Object, CreateSend >::OperationStateT< Rec >::Type", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type.html", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type" ],
    [ "dius::linux::RunSender< Object, CreateSend >::OperationStateT< Rec >::Type::Rec1", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type_1_1Rec1.html", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type_1_1Rec1" ],
    [ "dius::linux::RunSender< Object, CreateSend >::OperationStateT< Rec >::Type::Rec2", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type_1_1Rec2.html", "structdius_1_1linux_1_1RunSender_1_1OperationStateT_1_1Type_1_1Rec2" ],
    [ "dius::linux::enqueue_io_operation", "namespacedius_1_1linux.html#aece730450f5aed49a2994f35c64c9b0f", null ],
    [ "dius::linux::enqueue_operation", "namespacedius_1_1linux.html#aaac690af3ce20815ab782a677467042a", null ],
    [ "dius::linux::get_scheduler", "namespacedius_1_1linux.html#ab49fe8529bf1ba885a662cfa5d456183", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#aa8960877a46ac374ef288bcdea7de556", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#a468338ea1506056207ef6de43fca0444", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#a33206de1cc1dc214113a1ae64a249042", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#ae2d453f64851ada1983a0bdaec8ba18c", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#a1a5b508b6532ff015019b82c93c4d93f", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#a68af19919a0799236e6eb4937157d8f1", null ],
    [ "dius::linux::tag_invoke", "namespacedius_1_1linux.html#ac6315811baaa8c604c85a0bc76e7daf1", null ]
];