var ipc__binary_8h =
[
    [ "di::execution::ipc_binary_ns::Client", "structdi_1_1execution_1_1ipc__binary__ns_1_1Client.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1Client" ],
    [ "di::execution::ipc_binary_ns::Server", "structdi_1_1execution_1_1ipc__binary__ns_1_1Server.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1Server" ],
    [ "di::execution::ipc_binary_ns::MessageAtIndexHelper< Proto, ClientOrServer, message_index >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageAtIndexHelper.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageAtIndexHelper" ],
    [ "di::execution::ipc_binary_ns::MessageHeader", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageHeader.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageHeader" ],
    [ "di::execution::ipc_binary_ns::ReplyWaiterBase", "structdi_1_1execution_1_1ipc__binary__ns_1_1ReplyWaiterBase.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ReplyWaiterBase" ],
    [ "di::execution::ipc_binary_ns::ConnectionDataT< Proto, Read, Write, Alloc >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT" ],
    [ "di::execution::ipc_binary_ns::ConnectionDataT< Proto, Read, Write, Alloc >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionDataT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender::OperationStateT< Rec >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT" ],
    [ "di::execution::ipc_binary_ns::MessageDecode< Proto, ClientOrServer >::Sender::OperationStateT< Rec >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageDecode_1_1Sender_1_1OperationStateT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::MessageSequence< Proto, Read, Write, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageSequence.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MessageSequence" ],
    [ "di::execution::ipc_binary_ns::WaitForReplyOperationT< Proto, Read, Write, Alloc, ClientOrServer, message_index_, Rec >", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplyOperationT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplyOperationT" ],
    [ "di::execution::ipc_binary_ns::WaitForReplyOperationT< Proto, Read, Write, Alloc, ClientOrServer, message_index_, Rec >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplyOperationT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplyOperationT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::WaitForReplySenderT< Proto, Read, Write, Alloc, ClientOrServer, message_index >", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplySenderT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplySenderT" ],
    [ "di::execution::ipc_binary_ns::WaitForReplySenderT< Proto, Read, Write, Alloc, ClientOrServer, message_index >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplySenderT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1WaitForReplySenderT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::ConnectionTokenT< Proto, Read, Write, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT" ],
    [ "di::execution::ipc_binary_ns::ConnectionTokenT< Proto, Read, Write, Alloc, ClientOrServer >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectionTokenT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::FilterMessagesFunction< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1FilterMessagesFunction.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1FilterMessagesFunction" ],
    [ "di::execution::ipc_binary_ns::MakeJoinedSender< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1MakeJoinedSender.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1MakeJoinedSender" ],
    [ "di::execution::ipc_binary_ns::OperationStateT< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer, Rec >", "structdi_1_1execution_1_1ipc__binary__ns_1_1OperationStateT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1OperationStateT" ],
    [ "di::execution::ipc_binary_ns::OperationStateT< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer, Rec >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1OperationStateT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1OperationStateT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::SenderT< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer >", "structdi_1_1execution_1_1ipc__binary__ns_1_1SenderT.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SenderT" ],
    [ "di::execution::ipc_binary_ns::SenderT< Proto, Read, Write, TxFun, RxFun, Alloc, ClientOrServer >::Type", "structdi_1_1execution_1_1ipc__binary__ns_1_1SenderT_1_1Type.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1SenderT_1_1Type" ],
    [ "di::execution::ipc_binary_ns::DefaultTransmit", "structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultTransmit.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultTransmit" ],
    [ "di::execution::ipc_binary_ns::DefaultReceive", "structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultReceive.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultReceive" ],
    [ "di::execution::ipc_binary_ns::ConnectToClientFunction< Proto >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToClientFunction.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToClientFunction" ],
    [ "di::execution::ipc_binary_ns::ConnectToServerFunction< Proto >", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToServerFunction.html", "structdi_1_1execution_1_1ipc__binary__ns_1_1ConnectToServerFunction" ],
    [ "di::execution::ipc_binary_ns::ClientSender", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aed9c4137355d47336fcd2fa200be2605", null ],
    [ "di::execution::ipc_binary_ns::ConnectionData", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aa23e7730c341a62702377ff21aec952d", null ],
    [ "di::execution::ipc_binary_ns::ConnectionToken", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aed961f764104ad30af28075685767e98", null ],
    [ "di::execution::ipc_binary_ns::MessageAtIndex", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a48b1285752d79f34daa1931d1ae7dca4", null ],
    [ "di::execution::ipc_binary_ns::OperationState", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aea4dc952948f3b29c5de1680f9ffa212", null ],
    [ "di::execution::ipc_binary_ns::Peer", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a613809e243a509464cea141e5fd88fcc", null ],
    [ "di::execution::ipc_binary_ns::Sender", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aa6abf38adfc308673774ed9e711fc5c6", null ],
    [ "di::execution::ipc_binary_ns::ServerSender", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a66043507328c754f36952fd01d09826f", null ],
    [ "di::execution::ipc_binary_ns::WaitForReplyOperation", "namespacedi_1_1execution_1_1ipc__binary__ns.html#afe854394975bd6c785d4aac5d63a6133", null ],
    [ "di::execution::ipc_binary_ns::WaitForReplySender", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a716a7bc2b5b2cb08a467ef9adecfb7b9", null ],
    [ "di::execution::ipc_binary_ns::default_receive", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a7d0e0af795ba9f483138ded18f60e7cc", null ],
    [ "di::execution::ipc_binary_ns::default_transmit", "namespacedi_1_1execution_1_1ipc__binary__ns.html#aad4367433eb9bc2d614d848bafc68bf3", null ],
    [ "di::execution::ipc_binary_ns::filter_messages", "namespacedi_1_1execution_1_1ipc__binary__ns.html#ab744e651e4058ccf78803f4632eb6a28", null ],
    [ "di::execution::ipc_binary_connect_to_client", "namespacedi_1_1execution.html#a386071398ec9c52071a0754c9ca33e5e", null ],
    [ "di::ipc_binary_connect_to_client", "namespacedi.html#a386071398ec9c52071a0754c9ca33e5e", null ],
    [ "di::execution::ipc_binary_connect_to_server", "namespacedi_1_1execution.html#a542a5d23d60497ba23476a1b8a9238fe", null ],
    [ "di::ipc_binary_connect_to_server", "namespacedi.html#a542a5d23d60497ba23476a1b8a9238fe", null ],
    [ "di::execution::ipc_binary_ns::make_joined_sender", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a702f9a02fd28795fef0d7bdf8151b0ea", null ],
    [ "di::execution::ipc_binary_ns::message_decode", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a9427c72672e3f39749dedc8255fcbafb", null ],
    [ "di::execution::ipc_binary_ns::message_sequence", "namespacedi_1_1execution_1_1ipc__binary__ns.html#a0ebb41803cfcc4559859c13c91c68d3d", null ]
];