#pragma once

#include "di/reflect/enumerator.h"
#include "di/reflect/reflect.h"
#include "di/util/bitwise_enum.h"

// Key reference: https://sw.kovidgoyal.net/kitty/keyboard-protocol/
namespace ttx {
enum class Modifers {
    None = 0,
    Shift = 1 << 0,
    Alt = 1 << 1,
    Control = 1 << 2,
    Super = 1 << 3,
    Hyper = 1 << 4,
    Meta = 1 << 5,
    CapsLock = 1 << 6,
    NumLock = 1 << 7,
};

DI_DEFINE_ENUM_BITWISE_OPERATIONS(Modifers)

constexpr auto tag_invoke(di::Tag<di::reflect>, di::InPlaceType<Modifers>) {
    using enum Modifers;
    return di::make_enumerators(
        di::enumerator<"None", None>, di::enumerator<"Shift", Shift>, di::enumerator<"Alt", Alt>,
        di::enumerator<"Control", Control>, di::enumerator<"Super", Super>, di::enumerator<"Hyper", Hyper>,
        di::enumerator<"Meta", Meta>, di::enumerator<"CapsLock", CapsLock>, di::enumerator<"NumsLock", NumLock>);
}

enum class Key {
    None,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    _0,
    _1,
    _2,
    _3,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,

    Backtick,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    SemiColon,
    Quote,
    Comma,
    Period,
    Slash,

    Escape,
    Enter,
    Tab,
    Backspace,
    Space,
    Insert,
    Delete,
    Left,
    Right,
    Up,
    Down,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    Menu,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    F26,
    F27,
    F28,
    F29,
    F30,
    F31,
    F32,
    F33,
    F34,
    F35,

    KeyPad0,
    KeyPad1,
    KeyPad2,
    KeyPad3,
    KeyPad4,
    KeyPad5,
    KeyPad6,
    KeyPad7,
    KeyPad8,
    KeyPad9,
    KeyPadDecimal,
    KeyPadDivide,
    KeyPadMultiply,
    KeyPadSubtract,
    KeyPadAdd,
    KeyPadEnter,
    KeyPadEqual,
    KeyPadSeparator,
    KeyPadLeft,
    KeyPadRight,
    KeyPadUp,
    KeyPadDown,
    KeyPadPageUp,
    KeyPadPageDown,
    KeyPadHome,
    KeyPadEnd,
    KeyPadInsert,
    KeyPadDelete,
    KeyPadBegin,

    MediaPlay,
    MediaPause,
    MediaPlayPause,
    MediaReverse,
    MediaStop,
    MediaFastForward,
    MediaRewind,
    MediaTrackNext,
    MediaTrackPrevious,
    MediaRecord,
    LowerVolume,
    RaiseVolume,
    MuteVolume,

    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    LeftHyper,
    LeftMeta,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    RightHyper,
    RightMeta,
    IsoLevel3Shift,
    IsoLevel5Shift,

    KeyMax,
};

constexpr auto tag_invoke(di::Tag<di::reflect>, di::InPlaceType<Key>) {
    using enum Key;
    return di::make_enumerators(
        di::enumerator<"None", None>, di::enumerator<"A", A>, di::enumerator<"B", B>, di::enumerator<"C", C>,
        di::enumerator<"D", D>, di::enumerator<"E", E>, di::enumerator<"F", F>, di::enumerator<"G", G>,
        di::enumerator<"H", H>, di::enumerator<"I", I>, di::enumerator<"J", J>, di::enumerator<"K", K>,
        di::enumerator<"L", L>, di::enumerator<"M", M>, di::enumerator<"N", N>, di::enumerator<"O", O>,
        di::enumerator<"P", P>, di::enumerator<"Q", Q>, di::enumerator<"R", R>, di::enumerator<"S", S>,
        di::enumerator<"T", T>, di::enumerator<"U", U>, di::enumerator<"V", V>, di::enumerator<"W", W>,
        di::enumerator<"X", X>, di::enumerator<"Y", Y>, di::enumerator<"Z", Z>, di::enumerator<"0", _0>,
        di::enumerator<"1", _1>, di::enumerator<"2", _2>, di::enumerator<"3", _3>, di::enumerator<"4", _4>,
        di::enumerator<"5", _5>, di::enumerator<"6", _6>, di::enumerator<"7", _7>, di::enumerator<"8", _8>,
        di::enumerator<"9", _9>, di::enumerator<"Backtick", Backtick>, di::enumerator<"Minus", Minus>,
        di::enumerator<"Equal", Equal>, di::enumerator<"LeftBracket", LeftBracket>,
        di::enumerator<"RightBracket", RightBracket>, di::enumerator<"BackSlash", BackSlash>,
        di::enumerator<"SemiColon", SemiColon>, di::enumerator<"Quote", Quote>, di::enumerator<"Comma", Comma>,
        di::enumerator<"Period", Period>, di::enumerator<"Slash", Slash>, di::enumerator<"Escape", Escape>,
        di::enumerator<"Enter", Enter>, di::enumerator<"Tab", Tab>, di::enumerator<"Backspace", Backspace>,
        di::enumerator<"Space", Space>, di::enumerator<"Insert", Insert>, di::enumerator<"Delete", Delete>,
        di::enumerator<"Left", Left>, di::enumerator<"Right", Right>, di::enumerator<"Up", Up>,
        di::enumerator<"Down", Down>, di::enumerator<"PageUp", PageUp>, di::enumerator<"PageDown", PageDown>,
        di::enumerator<"Home", Home>, di::enumerator<"End", End>, di::enumerator<"CapsLock", CapsLock>,
        di::enumerator<"ScrollLock", ScrollLock>, di::enumerator<"NumLock", NumLock>,
        di::enumerator<"PrintScreen", PrintScreen>, di::enumerator<"Pause", Pause>, di::enumerator<"Menu", Menu>,
        di::enumerator<"F1", F1>, di::enumerator<"F2", F2>, di::enumerator<"F3", F3>, di::enumerator<"F4", F4>,
        di::enumerator<"F5", F5>, di::enumerator<"F6", F6>, di::enumerator<"F7", F7>, di::enumerator<"F8", F8>,
        di::enumerator<"F9", F9>, di::enumerator<"F10", F10>, di::enumerator<"F11", F11>, di::enumerator<"F12", F12>,
        di::enumerator<"F13", F13>, di::enumerator<"F14", F14>, di::enumerator<"F15", F15>, di::enumerator<"F16", F16>,
        di::enumerator<"F17", F17>, di::enumerator<"F18", F18>, di::enumerator<"F19", F19>, di::enumerator<"F20", F20>,
        di::enumerator<"F21", F21>, di::enumerator<"F22", F22>, di::enumerator<"F23", F23>, di::enumerator<"F24", F24>,
        di::enumerator<"F25", F25>, di::enumerator<"F26", F26>, di::enumerator<"F27", F27>, di::enumerator<"F28", F28>,
        di::enumerator<"F29", F29>, di::enumerator<"F30", F30>, di::enumerator<"F31", F31>, di::enumerator<"F32", F32>,
        di::enumerator<"F33", F33>, di::enumerator<"F34", F34>, di::enumerator<"F35", F35>,
        di::enumerator<"KeyPad0", KeyPad0>, di::enumerator<"KeyPad1", KeyPad1>, di::enumerator<"KeyPad2", KeyPad2>,
        di::enumerator<"KeyPad3", KeyPad3>, di::enumerator<"KeyPad4", KeyPad4>, di::enumerator<"KeyPad5", KeyPad5>,
        di::enumerator<"KeyPad6", KeyPad6>, di::enumerator<"KeyPad7", KeyPad7>, di::enumerator<"KeyPad8", KeyPad8>,
        di::enumerator<"KeyPad9", KeyPad9>, di::enumerator<"KeyPadDecimal", KeyPadDecimal>,
        di::enumerator<"KeyPadDivide", KeyPadDivide>, di::enumerator<"KeyPadMultiply", KeyPadMultiply>,
        di::enumerator<"KeyPadSubtract", KeyPadSubtract>, di::enumerator<"KeyPadAdd", KeyPadAdd>,
        di::enumerator<"KeyPadEnter", KeyPadEnter>, di::enumerator<"KeyPadEqual", KeyPadEqual>,
        di::enumerator<"KeyPadSeparator", KeyPadSeparator>, di::enumerator<"KeyPadLeft", KeyPadLeft>,
        di::enumerator<"KeyPadRight", KeyPadRight>, di::enumerator<"KeyPadUp", KeyPadUp>,
        di::enumerator<"KeyPadDown", KeyPadDown>, di::enumerator<"KeyPadPageUp", KeyPadPageUp>,
        di::enumerator<"KeyPadPageDown", KeyPadPageDown>, di::enumerator<"KeyPadHome", KeyPadHome>,
        di::enumerator<"KeyPadEnd", KeyPadEnd>, di::enumerator<"KeyPadInsert", KeyPadInsert>,
        di::enumerator<"KeyPadDelete", KeyPadDelete>, di::enumerator<"KeyPadBegin", KeyPadBegin>,
        di::enumerator<"MediaPlay", MediaPlay>, di::enumerator<"MediaPause", MediaPause>,
        di::enumerator<"MediaPlayPause", MediaPlayPause>, di::enumerator<"MediaReverse", MediaReverse>,
        di::enumerator<"MediaStop", MediaStop>, di::enumerator<"MediaFastForward", MediaFastForward>,
        di::enumerator<"MediaRewind", MediaRewind>, di::enumerator<"MediaTrackNext", MediaTrackNext>,
        di::enumerator<"MediaTrackPrevious", MediaTrackPrevious>, di::enumerator<"MediaRecord", MediaRecord>,
        di::enumerator<"LowerVolume", LowerVolume>, di::enumerator<"RaiseVolume", RaiseVolume>,
        di::enumerator<"MuteVolume", MuteVolume>, di::enumerator<"LeftShift", LeftShift>,
        di::enumerator<"LeftControl", LeftControl>, di::enumerator<"LeftAlt", LeftAlt>,
        di::enumerator<"LeftSuper", LeftSuper>, di::enumerator<"LeftHyper", LeftHyper>,
        di::enumerator<"LeftMeta", LeftMeta>, di::enumerator<"RightShift", RightShift>,
        di::enumerator<"RightControl", RightControl>, di::enumerator<"RightAlt", RightAlt>,
        di::enumerator<"RightSuper", RightSuper>, di::enumerator<"RightHyper", RightHyper>,
        di::enumerator<"RightMeta", RightMeta>, di::enumerator<"IsoLevel3Shift", IsoLevel3Shift>,
        di::enumerator<"IsoLevel5Shift", IsoLevel5Shift>);
}
}
