var searchData=
[
  ['dangling_0',['Dangling',['../structdi_1_1container_1_1Dangling.html',1,'di::container']]],
  ['datafunction_1',['DataFunction',['../structdi_1_1container_1_1DataFunction.html',1,'di::container']]],
  ['dataorcodesegment_2',['DataOrCodeSegment',['../structiris_1_1x86_1_1amd64_1_1sd_1_1DataOrCodeSegment.html',1,'iris::x86::amd64::sd']]],
  ['datat_3',['DataT',['../structdi_1_1execution_1_1bulk__ns_1_1DataT.html',1,'di::execution::bulk_ns::DataT&lt; Shape, Function, Rec &gt;'],['../structdi_1_1execution_1_1counting__scope__ns_1_1DataT.html',1,'di::execution::counting_scope_ns::DataT&lt; Alloc &gt;'],['../structdi_1_1execution_1_1filter__ns_1_1DataT.html',1,'di::execution::filter_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1first__value__ns_1_1DataT.html',1,'di::execution::first_value_ns::DataT&lt; Seq, Rec &gt;'],['../structdi_1_1execution_1_1from__container__ns_1_1DataT.html',1,'di::execution::from_container_ns::DataT&lt; Con, Rec &gt;'],['../structdi_1_1execution_1_1ignore__all__ns_1_1DataT.html',1,'di::execution::ignore_all_ns::DataT&lt; Seq, Rec &gt;'],['../structdi_1_1execution_1_1let__ns_1_1DataT.html',1,'di::execution::let_ns::DataT&lt; CPO, Rec, Fun, Completions &gt;'],['../structdi_1_1execution_1_1schedule__from__ns_1_1DataT.html',1,'di::execution::schedule_from_ns::DataT&lt; Rec, Sched, Completions &gt;'],['../structdi_1_1execution_1_1start__detached__ns_1_1DataT.html',1,'di::execution::start_detached_ns::DataT&lt; Alloc &gt;'],['../structdi_1_1execution_1_1then__ns_1_1DataT.html',1,'di::execution::then_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1transform__each__ns_1_1DataT.html',1,'di::execution::transform_each_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1when__all__ns_1_1DataT.html',1,'di::execution::when_all_ns::DataT&lt; Rec, Sends &gt;']]],
  ['deallocatefunction_4',['DeallocateFunction',['../structdi_1_1container_1_1detail_1_1DeallocateFunction.html',1,'di::container::detail']]],
  ['deallocatemanyfunction_5',['DeallocateManyFunction',['../structdi_1_1container_1_1detail_1_1DeallocateManyFunction.html',1,'di::container::detail']]],
  ['deallocateonefunction_6',['DeallocateOneFunction',['../structdi_1_1container_1_1detail_1_1DeallocateOneFunction.html',1,'di::container::detail']]],
  ['debugfile_7',['DebugFile',['../structiris_1_1DebugFile.html',1,'iris']]],
  ['debugformatcontext_8',['DebugFormatContext',['../structiris_1_1detail_1_1DebugFormatContext.html',1,'iris::detail']]],
  ['debugfunction_9',['DebugFunction',['../structdi_1_1execution_1_1with__env__ns_1_1DebugFunction.html',1,'di::execution::with_env_ns']]],
  ['deducecreatefunction_10',['DeduceCreateFunction',['../structdi_1_1util_1_1detail_1_1DeduceCreateFunction.html',1,'di::util::detail']]],
  ['defaultaccessor_11',['DefaultAccessor',['../classdi_1_1vocab_1_1DefaultAccessor.html',1,'di::vocab']]],
  ['defaultconstructatfunction_12',['DefaultConstructAtFunction',['../structdi_1_1util_1_1detail_1_1DefaultConstructAtFunction.html',1,'di::util::detail']]],
  ['defaultdelete_13',['DefaultDelete',['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab']]],
  ['defaultdelete_3c_20iris_3a_3asuperblock_20_3e_14',['DefaultDelete&lt; iris::SuperBlock &gt;',['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab']]],
  ['defaulthasher_15',['DefaultHasher',['../structdi_1_1container_1_1DefaultHasher.html',1,'di::container']]],
  ['defaultintrusiveforwardlisttag_16',['DefaultIntrusiveForwardListTag',['../structdi_1_1container_1_1DefaultIntrusiveForwardListTag.html',1,'di::container']]],
  ['defaultintrusivehashsettag_17',['DefaultIntrusiveHashSetTag',['../structdi_1_1container_1_1DefaultIntrusiveHashSetTag.html',1,'di::container']]],
  ['defaultintrusivelisttag_18',['DefaultIntrusiveListTag',['../structdi_1_1container_1_1DefaultIntrusiveListTag.html',1,'di::container']]],
  ['defaultintrusivetreesettag_19',['DefaultIntrusiveTreeSetTag',['../structdi_1_1container_1_1DefaultIntrusiveTreeSetTag.html',1,'di::container']]],
  ['defaultreceive_20',['DefaultReceive',['../structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultReceive.html',1,'di::execution::ipc_binary_ns']]],
  ['defaultsentinel_21',['DefaultSentinel',['../structdi_1_1container_1_1DefaultSentinel.html',1,'di::container']]],
  ['defaulttransmit_22',['DefaultTransmit',['../structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultTransmit.html',1,'di::execution::ipc_binary_ns']]],
  ['defer_23',['Defer',['../structdi_1_1meta_1_1Defer.html',1,'di::meta']]],
  ['deferconstruct_24',['DeferConstruct',['../classdi_1_1util_1_1DeferConstruct.html',1,'di::util']]],
  ['deferhelper_25',['DeferHelper',['../structdi_1_1meta_1_1detail_1_1DeferHelper.html',1,'di::meta::detail']]],
  ['deferhelper_3c_20fun_2c_20args_2e_2e_2e_20_3e_26',['DeferHelper&lt; Fun, Args... &gt;',['../structdi_1_1meta_1_1detail_1_1DeferHelper_3_01Fun_00_01Args_8_8_8_01_4.html',1,'di::meta::detail']]],
  ['definitelyequalitycomparablewith_27',['DefinitelyEqualityComparableWith',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3aarray_2c_20serialization_3a_3ajson_3a_3aarray_20_3e_28',['DefinitelyEqualityComparableWith&lt; serialization::json::Array, serialization::json::Array &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith_3_01serialization_1_1json_1_159fc8623473873917e1e7ae27c484d25.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3akeyvalue_2c_20serialization_3a_3ajson_3a_3akeyvalue_20_3e_29',['DefinitelyEqualityComparableWith&lt; serialization::json::KeyValue, serialization::json::KeyValue &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith_3_01serialization_1_1json_1_19d76e67b318d303df815bff61af52f3d.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3aobject_2c_20serialization_3a_3ajson_3a_3aobject_20_3e_30',['DefinitelyEqualityComparableWith&lt; serialization::json::Object, serialization::json::Object &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith_3_01serialization_1_1json_1_1cf5bc8688ef1b23fe8acbd2513e0d7e0.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3avalue_2c_20serialization_3a_3ajson_3a_3avalue_20_3e_31',['DefinitelyEqualityComparableWith&lt; serialization::json::Value, serialization::json::Value &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith_3_01serialization_1_1json_1_1cebd9575d37a2582c010b74ba6d860c5.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_32',['DefinitelyThreeWayComparableWith',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3aarray_2c_20serialization_3a_3ajson_3a_3aarray_20_3e_33',['DefinitelyThreeWayComparableWith&lt; serialization::json::Array, serialization::json::Array &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith_3_01serialization_1_1json_1_1b9ece0c05be2d1cb95be535c6081d9d0.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3akeyvalue_2c_20serialization_3a_3ajson_3a_3akeyvalue_20_3e_34',['DefinitelyThreeWayComparableWith&lt; serialization::json::KeyValue, serialization::json::KeyValue &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith_3_01serialization_1_1json_1_13bb4e2d742f80b495b084f5c401528db.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3aobject_2c_20serialization_3a_3ajson_3a_3aobject_20_3e_35',['DefinitelyThreeWayComparableWith&lt; serialization::json::Object, serialization::json::Object &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith_3_01serialization_1_1json_1_1091e0060a111e3b1f021ec3477bd417b.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3avalue_2c_20serialization_3a_3ajson_3a_3avalue_20_3e_36',['DefinitelyThreeWayComparableWith&lt; serialization::json::Value, serialization::json::Value &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith_3_01serialization_1_1json_1_1c120b09b392f8e67305d2c82bf201d60.html',1,'di::concepts::detail']]],
  ['dereference_37',['Dereference',['../structdi_1_1function_1_1Dereference.html',1,'di::function']]],
  ['deserializablefunction_38',['DeserializableFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializableFunction.html',1,'di::serialization::detail']]],
  ['deserializebinaryfunction_39',['DeserializeBinaryFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeBinaryFunction.html',1,'di::serialization::detail']]],
  ['deserializefunction_40',['DeserializeFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeFunction.html',1,'di::serialization::detail']]],
  ['deserializeinplacefunction_41',['DeserializeInPlaceFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeInPlaceFunction.html',1,'di::serialization::detail']]],
  ['deserializejsonfunction_42',['DeserializeJsonFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeJsonFunction.html',1,'di::serialization::detail']]],
  ['deserializemetadatafunction_43',['DeserializeMetadataFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeMetadataFunction.html',1,'di::serialization::detail']]],
  ['deserializerfunction_44',['DeserializerFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializerFunction.html',1,'di::serialization::detail']]],
  ['deserializestringfunction_45',['DeserializeStringFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeStringFunction.html',1,'di::serialization::detail']]],
  ['destroyatfunction_46',['DestroyAtFunction',['../structdi_1_1util_1_1detail_1_1DestroyAtFunction.html',1,'di::util::detail']]],
  ['destroyfunction_47',['DestroyFunction',['../structdi_1_1container_1_1detail_1_1DestroyFunction.html',1,'di::container::detail']]],
  ['destroynfunction_48',['DestroyNFunction',['../structdi_1_1container_1_1detail_1_1DestroyNFunction.html',1,'di::container::detail']]],
  ['dextentshelper_49',['DextentsHelper',['../structdi_1_1vocab_1_1detail_1_1DextentsHelper.html',1,'di::vocab::detail']]],
  ['dextentshelper_3c_20sizetype_2c_20meta_3a_3alist_3c_20constexpr_3c_20extents_20_3e_2e_2e_2e_20_3e_20_3e_50',['DextentsHelper&lt; SizeType, meta::List&lt; Constexpr&lt; extents &gt;... &gt; &gt;',['../structdi_1_1vocab_1_1detail_1_1DextentsHelper_3_01SizeType_00_01meta_1_1List_3_01Constexpr_3_01extents_01_4_8_8_8_01_4_01_4.html',1,'di::vocab::detail']]],
  ['directoryentry_51',['DirectoryEntry',['../classdius_1_1filesystem_1_1DirectoryEntry.html',1,'dius::filesystem::DirectoryEntry'],['../structiris_1_1initrd_1_1DirectoryEntry.html',1,'iris::initrd::DirectoryEntry']]],
  ['directoryiterator_52',['DirectoryIterator',['../classdius_1_1filesystem_1_1DirectoryIterator.html',1,'dius::filesystem']]],
  ['directoryrecord_53',['DirectoryRecord',['../structiris_1_1DirectoryRecord.html',1,'iris']]],
  ['dirent_54',['Dirent',['../structdius_1_1linux_1_1Dirent.html',1,'dius::linux']]],
  ['direntiterator_55',['DirentIterator',['../classiris_1_1DirentIterator.html',1,'iris']]],
  ['dirty_56',['Dirty',['../structiris_1_1x86_1_1amd64_1_1page__structure_1_1Dirty.html',1,'iris::x86::amd64::page_structure']]],
  ['disabledestruction_57',['DisableDestruction',['../classiris_1_1DisableDestruction.html',1,'iris']]],
  ['disableirqline_58',['DisableIrqLine',['../structiris_1_1detail_1_1DisableIrqLine.html',1,'iris::detail']]],
  ['dispatcherimpl_59',['DispatcherImpl',['../structdi_1_1any_1_1detail_1_1DispatcherImpl.html',1,'di::any::detail']]],
  ['dispatcherimpl_3c_20tag_2c_20r_28self_2c_20args_2e_2e_2e_29_2c_20tags_2e_2e_2e_20_3e_60',['DispatcherImpl&lt; Tag, R(Self, Args...), Tags... &gt;',['../structdi_1_1any_1_1detail_1_1DispatcherImpl_3_01Tag_00_01R_07Self_00_01Args_8_8_8_08_00_01Tags_8_8_8_01_4.html',1,'di::any::detail']]],
  ['distancefunction_61',['DistanceFunction',['../structdi_1_1container_1_1detail_1_1DistanceFunction.html',1,'di::container::detail']]],
  ['div_5ft_62',['div_t',['../structdiv__t.html',1,'']]],
  ['divideroundupfunction_63',['DivideRoundUpFunction',['../structdi_1_1math_1_1detail_1_1DivideRoundUpFunction.html',1,'di::math::detail']]],
  ['dpl_64',['DPL',['../structiris_1_1x86_1_1amd64_1_1idt_1_1DPL.html',1,'iris::x86::amd64::idt::DPL'],['../structiris_1_1x86_1_1amd64_1_1sd_1_1DPL.html',1,'iris::x86::amd64::sd::DPL'],['../structiris_1_1x86_1_1amd64_1_1ssd_1_1DPL.html',1,'iris::x86::amd64::ssd::DPL']]],
  ['dropfunction_65',['DropFunction',['../structdi_1_1container_1_1view_1_1detail_1_1DropFunction.html',1,'di::container::view::detail']]],
  ['droppagefunction_66',['DropPageFunction',['../structiris_1_1mm_1_1detail_1_1DropPageFunction.html',1,'iris::mm::detail']]],
  ['dropview_67',['DropView',['../classdi_1_1container_1_1DropView.html',1,'di::container']]],
  ['dropwhilefunction_68',['DropWhileFunction',['../structdi_1_1container_1_1view_1_1detail_1_1DropWhileFunction.html',1,'di::container::view::detail']]],
  ['dropwhileview_69',['DropWhileView',['../classdi_1_1container_1_1DropWhileView.html',1,'di::container']]],
  ['dumbspinlock_70',['DumbSpinlock',['../classdi_1_1sync_1_1DumbSpinlock.html',1,'di::sync']]],
  ['dummyoperationstate_71',['DummyOperationState',['../structdi_1_1execution_1_1dummy__ns_1_1DummyOperationState.html',1,'di::execution::dummy_ns']]],
  ['dummypromise_72',['DummyPromise',['../structdi_1_1execution_1_1as__awaitable__ns_1_1DummyPromise.html',1,'di::execution::as_awaitable_ns']]],
  ['dummyreturnobject_73',['DummyReturnObject',['../structdi_1_1execution_1_1detail_1_1DummyReturnObject.html',1,'di::execution::detail']]],
  ['dummysenderof_74',['DummySenderOf',['../structdi_1_1execution_1_1dummy__ns_1_1DummySenderOf.html',1,'di::execution::dummy_ns']]],
  ['duration_75',['Duration',['../classdi_1_1chrono_1_1Duration.html',1,'di::chrono']]],
  ['durationcastfunction_76',['DurationCastFunction',['../structdi_1_1chrono_1_1detail_1_1DurationCastFunction.html',1,'di::chrono::detail']]]
];
