var searchData=
[
  ['dangling_0',['Dangling',['../structdi_1_1container_1_1Dangling.html',1,'di::container']]],
  ['datafunction_1',['DataFunction',['../structdi_1_1container_1_1DataFunction.html',1,'di::container']]],
  ['dataorcodesegment_2',['DataOrCodeSegment',['../structiris_1_1x86_1_1amd64_1_1sd_1_1DataOrCodeSegment.html',1,'iris::x86::amd64::sd']]],
  ['datat_3',['DataT',['../structdi_1_1execution_1_1bulk__ns_1_1DataT.html',1,'di::execution::bulk_ns::DataT&lt; Shape, Function, Rec &gt;'],['../structdi_1_1execution_1_1counting__scope__ns_1_1DataT.html',1,'di::execution::counting_scope_ns::DataT&lt; Alloc &gt;'],['../structdi_1_1execution_1_1filter__ns_1_1DataT.html',1,'di::execution::filter_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1first__value__ns_1_1DataT.html',1,'di::execution::first_value_ns::DataT&lt; Seq, Rec &gt;'],['../structdi_1_1execution_1_1from__container__ns_1_1DataT.html',1,'di::execution::from_container_ns::DataT&lt; Con, Rec &gt;'],['../structdi_1_1execution_1_1ignore__all__ns_1_1DataT.html',1,'di::execution::ignore_all_ns::DataT&lt; Seq, Rec &gt;'],['../structdi_1_1execution_1_1let__ns_1_1DataT.html',1,'di::execution::let_ns::DataT&lt; CPO, Rec, Fun, Completions &gt;'],['../structdi_1_1execution_1_1schedule__from__ns_1_1DataT.html',1,'di::execution::schedule_from_ns::DataT&lt; Rec, Sched, Completions &gt;'],['../structdi_1_1execution_1_1start__detached__ns_1_1DataT.html',1,'di::execution::start_detached_ns::DataT&lt; Alloc &gt;'],['../structdi_1_1execution_1_1then__ns_1_1DataT.html',1,'di::execution::then_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1transform__each__ns_1_1DataT.html',1,'di::execution::transform_each_ns::DataT&lt; Fun, Rec &gt;'],['../structdi_1_1execution_1_1when__all__ns_1_1DataT.html',1,'di::execution::when_all_ns::DataT&lt; Rec, Sends &gt;']]],
  ['dcs_4',['DCS',['../structttx_1_1DCS.html',1,'ttx']]],
  ['deallocatefunction_5',['DeallocateFunction',['../structdi_1_1container_1_1detail_1_1DeallocateFunction.html',1,'di::container::detail']]],
  ['deallocatemanyfunction_6',['DeallocateManyFunction',['../structdi_1_1container_1_1detail_1_1DeallocateManyFunction.html',1,'di::container::detail']]],
  ['deallocateonefunction_7',['DeallocateOneFunction',['../structdi_1_1container_1_1detail_1_1DeallocateOneFunction.html',1,'di::container::detail']]],
  ['debugfile_8',['DebugFile',['../structiris_1_1DebugFile.html',1,'iris']]],
  ['debugformatcontext_9',['DebugFormatContext',['../structiris_1_1detail_1_1DebugFormatContext.html',1,'iris::detail']]],
  ['debugfunction_10',['DebugFunction',['../structdi_1_1execution_1_1with__env__ns_1_1DebugFunction.html',1,'di::execution::with_env_ns']]],
  ['deducecreatefunction_11',['DeduceCreateFunction',['../structdi_1_1util_1_1detail_1_1DeduceCreateFunction.html',1,'di::util::detail']]],
  ['defaultaccessor_12',['DefaultAccessor',['../classdi_1_1DefaultAccessor.html',1,'di::DefaultAccessor&lt; Element &gt;'],['../classdi_1_1vocab_1_1DefaultAccessor.html',1,'di::vocab::DefaultAccessor&lt; Element &gt;']]],
  ['defaultconstructatfunction_13',['DefaultConstructAtFunction',['../structdi_1_1util_1_1detail_1_1DefaultConstructAtFunction.html',1,'di::util::detail']]],
  ['defaultdelete_14',['DefaultDelete',['../structdi_1_1DefaultDelete.html',1,'di::DefaultDelete&lt; T &gt;'],['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab::DefaultDelete&lt; T &gt;']]],
  ['defaultdelete_3c_20iris_3a_3asuperblock_20_3e_15',['DefaultDelete&lt; iris::SuperBlock &gt;',['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab']]],
  ['defaultdelete_3c_20ttx_3a_3apane_20_3e_16',['DefaultDelete&lt; ttx::Pane &gt;',['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab']]],
  ['defaultdelete_3c_20ttx_3a_3aterminal_20_3e_17',['DefaultDelete&lt; ttx::Terminal &gt;',['../structdi_1_1vocab_1_1DefaultDelete.html',1,'di::vocab']]],
  ['defaulthasher_18',['DefaultHasher',['../structdi_1_1container_1_1DefaultHasher.html',1,'di::container::DefaultHasher'],['../structdi_1_1DefaultHasher.html',1,'di::DefaultHasher']]],
  ['defaultintrusiveforwardlisttag_19',['DefaultIntrusiveForwardListTag',['../structdi_1_1container_1_1DefaultIntrusiveForwardListTag.html',1,'di::container']]],
  ['defaultintrusivehashsettag_20',['DefaultIntrusiveHashSetTag',['../structdi_1_1container_1_1DefaultIntrusiveHashSetTag.html',1,'di::container']]],
  ['defaultintrusivelisttag_21',['DefaultIntrusiveListTag',['../structdi_1_1container_1_1DefaultIntrusiveListTag.html',1,'di::container']]],
  ['defaultintrusivetreesettag_22',['DefaultIntrusiveTreeSetTag',['../structdi_1_1container_1_1DefaultIntrusiveTreeSetTag.html',1,'di::container']]],
  ['defaultreceive_23',['DefaultReceive',['../structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultReceive.html',1,'di::execution::ipc_binary_ns']]],
  ['defaultsentinel_24',['DefaultSentinel',['../structdi_1_1container_1_1DefaultSentinel.html',1,'di::container::DefaultSentinel'],['../structdi_1_1DefaultSentinel.html',1,'di::DefaultSentinel']]],
  ['defaulttransmit_25',['DefaultTransmit',['../structdi_1_1execution_1_1ipc__binary__ns_1_1DefaultTransmit.html',1,'di::execution::ipc_binary_ns']]],
  ['deferconstruct_26',['DeferConstruct',['../classdi_1_1DeferConstruct.html',1,'di::DeferConstruct&lt; Fun &gt;'],['../classdi_1_1util_1_1DeferConstruct.html',1,'di::util::DeferConstruct&lt; Fun &gt;']]],
  ['deferhelper_27',['DeferHelper',['../structdi_1_1meta_1_1detail_1_1DeferHelper.html',1,'di::meta::detail']]],
  ['deferhelper_3c_20fun_2c_20args_2e_2e_2e_20_3e_28',['DeferHelper&lt; Fun, Args... &gt;',['../structdi_1_1meta_1_1detail_1_1DeferHelper.html',1,'di::meta::detail']]],
  ['definitelyequalitycomparablewith_29',['DefinitelyEqualityComparableWith',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3aarray_2c_20serialization_3a_3ajson_3a_3aarray_20_3e_30',['DefinitelyEqualityComparableWith&lt; serialization::json::Array, serialization::json::Array &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3akeyvalue_2c_20serialization_3a_3ajson_3a_3akeyvalue_20_3e_31',['DefinitelyEqualityComparableWith&lt; serialization::json::KeyValue, serialization::json::KeyValue &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3aobject_2c_20serialization_3a_3ajson_3a_3aobject_20_3e_32',['DefinitelyEqualityComparableWith&lt; serialization::json::Object, serialization::json::Object &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelyequalitycomparablewith_3c_20serialization_3a_3ajson_3a_3avalue_2c_20serialization_3a_3ajson_3a_3avalue_20_3e_33',['DefinitelyEqualityComparableWith&lt; serialization::json::Value, serialization::json::Value &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyEqualityComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_34',['DefinitelyThreeWayComparableWith',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3aarray_2c_20serialization_3a_3ajson_3a_3aarray_20_3e_35',['DefinitelyThreeWayComparableWith&lt; serialization::json::Array, serialization::json::Array &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3akeyvalue_2c_20serialization_3a_3ajson_3a_3akeyvalue_20_3e_36',['DefinitelyThreeWayComparableWith&lt; serialization::json::KeyValue, serialization::json::KeyValue &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3aobject_2c_20serialization_3a_3ajson_3a_3aobject_20_3e_37',['DefinitelyThreeWayComparableWith&lt; serialization::json::Object, serialization::json::Object &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['definitelythreewaycomparablewith_3c_20serialization_3a_3ajson_3a_3avalue_2c_20serialization_3a_3ajson_3a_3avalue_20_3e_38',['DefinitelyThreeWayComparableWith&lt; serialization::json::Value, serialization::json::Value &gt;',['../structdi_1_1concepts_1_1detail_1_1DefinitelyThreeWayComparableWith.html',1,'di::concepts::detail']]],
  ['dereference_39',['Dereference',['../structdi_1_1Dereference.html',1,'di::Dereference'],['../structdi_1_1function_1_1Dereference.html',1,'di::function::Dereference']]],
  ['deserializablefunction_40',['DeserializableFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializableFunction.html',1,'di::serialization::detail']]],
  ['deserializebinaryfunction_41',['DeserializeBinaryFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeBinaryFunction.html',1,'di::serialization::detail']]],
  ['deserializefunction_42',['DeserializeFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeFunction.html',1,'di::serialization::detail']]],
  ['deserializeinplacefunction_43',['DeserializeInPlaceFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeInPlaceFunction.html',1,'di::serialization::detail']]],
  ['deserializejsonfunction_44',['DeserializeJsonFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeJsonFunction.html',1,'di::serialization::detail']]],
  ['deserializemetadatafunction_45',['DeserializeMetadataFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeMetadataFunction.html',1,'di::serialization::detail']]],
  ['deserializerfunction_46',['DeserializerFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializerFunction.html',1,'di::serialization::detail']]],
  ['deserializestringfunction_47',['DeserializeStringFunction',['../structdi_1_1serialization_1_1detail_1_1DeserializeStringFunction.html',1,'di::serialization::detail']]],
  ['destroyatfunction_48',['DestroyAtFunction',['../structdi_1_1util_1_1detail_1_1DestroyAtFunction.html',1,'di::util::detail']]],
  ['destroyfunction_49',['DestroyFunction',['../structdi_1_1container_1_1detail_1_1DestroyFunction.html',1,'di::container::detail']]],
  ['destroynfunction_50',['DestroyNFunction',['../structdi_1_1container_1_1detail_1_1DestroyNFunction.html',1,'di::container::detail']]],
  ['dextentshelper_51',['DextentsHelper',['../structdi_1_1vocab_1_1detail_1_1DextentsHelper.html',1,'di::vocab::detail']]],
  ['dextentshelper_3c_20sizetype_2c_20meta_3a_3alist_3c_20constexpr_3c_20extents_20_3e_2e_2e_2e_20_3e_20_3e_52',['DextentsHelper&lt; SizeType, meta::List&lt; Constexpr&lt; extents &gt;... &gt; &gt;',['../structdi_1_1vocab_1_1detail_1_1DextentsHelper.html',1,'di::vocab::detail']]],
  ['directoryentry_53',['DirectoryEntry',['../classdius_1_1filesystem_1_1DirectoryEntry.html',1,'dius::filesystem::DirectoryEntry'],['../structiris_1_1initrd_1_1DirectoryEntry.html',1,'iris::initrd::DirectoryEntry']]],
  ['directoryiterator_54',['DirectoryIterator',['../classdius_1_1filesystem_1_1DirectoryIterator.html',1,'dius::filesystem']]],
  ['directoryrecord_55',['DirectoryRecord',['../structiris_1_1DirectoryRecord.html',1,'iris']]],
  ['dirent_56',['Dirent',['../structdius_1_1linux_1_1Dirent.html',1,'dius::linux']]],
  ['direntiterator_57',['DirentIterator',['../classiris_1_1DirentIterator.html',1,'iris']]],
  ['dirty_58',['Dirty',['../structiris_1_1x86_1_1amd64_1_1page__structure_1_1Dirty.html',1,'iris::x86::amd64::page_structure']]],
  ['disabledestruction_59',['DisableDestruction',['../classiris_1_1DisableDestruction.html',1,'iris']]],
  ['disableirqline_60',['DisableIrqLine',['../structiris_1_1detail_1_1DisableIrqLine.html',1,'iris::detail']]],
  ['dispatcherimpl_61',['DispatcherImpl',['../structdi_1_1any_1_1detail_1_1DispatcherImpl.html',1,'di::any::detail']]],
  ['dispatcherimpl_3c_20tag_2c_20r_28self_2c_20args_2e_2e_2e_29_2c_20tags_2e_2e_2e_20_3e_62',['DispatcherImpl&lt; Tag, R(Self, Args...), Tags... &gt;',['../structdi_1_1any_1_1detail_1_1DispatcherImpl.html',1,'di::any::detail']]],
  ['distancefunction_63',['DistanceFunction',['../structdi_1_1container_1_1detail_1_1DistanceFunction.html',1,'di::container::detail']]],
  ['div_5ft_64',['div_t',['../structdiv__t.html',1,'']]],
  ['divideroundupfunction_65',['DivideRoundUpFunction',['../structdi_1_1math_1_1detail_1_1DivideRoundUpFunction.html',1,'di::math::detail']]],
  ['dpl_66',['DPL',['../structiris_1_1x86_1_1amd64_1_1idt_1_1DPL.html',1,'iris::x86::amd64::idt::DPL'],['../structiris_1_1x86_1_1amd64_1_1sd_1_1DPL.html',1,'iris::x86::amd64::sd::DPL'],['../structiris_1_1x86_1_1amd64_1_1ssd_1_1DPL.html',1,'iris::x86::amd64::ssd::DPL']]],
  ['drawcircle_67',['DrawCircle',['../structgfx_1_1painter_1_1DrawCircle.html',1,'gfx::painter']]],
  ['drawrect_68',['DrawRect',['../structgfx_1_1painter_1_1DrawRect.html',1,'gfx::painter']]],
  ['dropfunction_69',['DropFunction',['../structdi_1_1container_1_1view_1_1detail_1_1DropFunction.html',1,'di::container::view::detail']]],
  ['droppagefunction_70',['DropPageFunction',['../structiris_1_1mm_1_1detail_1_1DropPageFunction.html',1,'iris::mm::detail']]],
  ['dropview_71',['DropView',['../classdi_1_1container_1_1DropView.html',1,'di::container']]],
  ['dropwhilefunction_72',['DropWhileFunction',['../structdi_1_1container_1_1view_1_1detail_1_1DropWhileFunction.html',1,'di::container::view::detail']]],
  ['dropwhileview_73',['DropWhileView',['../classdi_1_1container_1_1DropWhileView.html',1,'di::container']]],
  ['dumbspinlock_74',['DumbSpinlock',['../classdi_1_1DumbSpinlock.html',1,'di::DumbSpinlock'],['../classdi_1_1sync_1_1DumbSpinlock.html',1,'di::sync::DumbSpinlock']]],
  ['dummyoperationstate_75',['DummyOperationState',['../structdi_1_1execution_1_1dummy__ns_1_1DummyOperationState.html',1,'di::execution::dummy_ns']]],
  ['dummypromise_76',['DummyPromise',['../structdi_1_1execution_1_1as__awaitable__ns_1_1DummyPromise.html',1,'di::execution::as_awaitable_ns']]],
  ['dummyreturnobject_77',['DummyReturnObject',['../structdi_1_1execution_1_1detail_1_1DummyReturnObject.html',1,'di::execution::detail']]],
  ['dummysenderof_78',['DummySenderOf',['../structdi_1_1execution_1_1dummy__ns_1_1DummySenderOf.html',1,'di::execution::dummy_ns']]],
  ['duration_79',['Duration',['../classdi_1_1chrono_1_1Duration.html',1,'di::chrono::Duration&lt; Rep, Period &gt;'],['../classdi_1_1Duration.html',1,'di::Duration&lt; Rep, Period &gt;']]],
  ['durationcastfunction_80',['DurationCastFunction',['../structdi_1_1chrono_1_1detail_1_1DurationCastFunction.html',1,'di::chrono::detail']]]
];
