export LIBRARY=$(BUILDDIR)/libs/libpthread/libpthread.a
export OBJS=\
$(BUILDDIR)/libs/libpthread/mutex.o \
$(BUILDDIR)/libs/libpthread/pthread.o \
$(BUILDDIR)/libs/libpthread/spinlock.o

include ../Makefile.common