OBJS=\
$(BUILDDIR)/userland/sh/builtin.o \
$(BUILDDIR)/userland/sh/command.o \
$(BUILDDIR)/userland/sh/input.o \
$(BUILDDIR)/userland/sh/main.o \
$(BUILDDIR)/userland/sh/parser.o

EXECUTABLE=$(BUILDDIR)/userland/sh/sh

CFLAGS+=-D_OS_2_SOURCE

include $(ROOT)/userland/Makefile.common