#pragma once

#include <di/container/concepts/bidirectional_container.h>
#include <di/container/concepts/bidirectional_iterator.h>
#include <di/container/concepts/borrowed_container.h>
#include <di/container/concepts/common_container.h>
#include <di/container/concepts/constant_container.h>
#include <di/container/concepts/container.h>
#include <di/container/concepts/container_compatible.h>
#include <di/container/concepts/container_iterator_reconstructible_container.h>
#include <di/container/concepts/container_of.h>
#include <di/container/concepts/contiguous_container.h>
#include <di/container/concepts/contiguous_iterator.h>
#include <di/container/concepts/forward_container.h>
#include <di/container/concepts/forward_iterator.h>
#include <di/container/concepts/indirect_binary_predicate.h>
#include <di/container/concepts/indirect_equivalence_relation.h>
#include <di/container/concepts/indirect_strict_weak_order.h>
#include <di/container/concepts/indirect_unary_predicate.h>
#include <di/container/concepts/indirectly_binary_left_foldable.h>
#include <di/container/concepts/indirectly_binary_right_foldable.h>
#include <di/container/concepts/indirectly_comparable.h>
#include <di/container/concepts/indirectly_copyable.h>
#include <di/container/concepts/indirectly_copyable_storable.h>
#include <di/container/concepts/indirectly_movable.h>
#include <di/container/concepts/indirectly_movable_storable.h>
#include <di/container/concepts/indirectly_readable.h>
#include <di/container/concepts/indirectly_regular_unary_invocable.h>
#include <di/container/concepts/indirectly_swappable.h>
#include <di/container/concepts/indirectly_unary_invocable.h>
#include <di/container/concepts/indirectly_writable.h>
#include <di/container/concepts/input_container.h>
#include <di/container/concepts/input_iterator.h>
#include <di/container/concepts/iterator.h>
#include <di/container/concepts/iterator_reconstructible_container.h>
#include <di/container/concepts/mergeable.h>
#include <di/container/concepts/output_container.h>
#include <di/container/concepts/output_iterator.h>
#include <di/container/concepts/permutable.h>
#include <di/container/concepts/random_access_container.h>
#include <di/container/concepts/random_access_iterator.h>
#include <di/container/concepts/reconstructible_container.h>
#include <di/container/concepts/sentinel_for.h>
#include <di/container/concepts/simple_view.h>
#include <di/container/concepts/sized_container.h>
#include <di/container/concepts/sized_sentinel_for.h>
#include <di/container/concepts/sortable.h>
#include <di/container/concepts/uninit_bidirectional_container.h>
#include <di/container/concepts/uninit_bidirectional_iterator.h>
#include <di/container/concepts/uninit_forward_container.h>
#include <di/container/concepts/uninit_forward_iterator.h>
#include <di/container/concepts/uninit_input_container.h>
#include <di/container/concepts/uninit_input_iterator.h>
#include <di/container/concepts/uninit_sentinel_for.h>
#include <di/container/concepts/view.h>
#include <di/container/concepts/viewable_container.h>
#include <di/container/concepts/weakly_incrementable.h>