#ifndef _KERNEL_HAL_X86_64_DRIVERS_IDE_CONTROLLER_H
#define _KERNEL_HAL_X86_64_DRIVERS_IDE_CONTROLLER_H 1

#include <kernel/hal/pci.h>

#define IDE_CONTROLLER_IF_PRIMARY_MODE_SELECT         (1 << 0)
#define IDE_CONTROLLER_IF_PRIMARY_MODE_CAPABILITIES   (1 << 1)
#define IDE_CONTROLLER_IF_SECONDARY_MODE_SELECT       (1 << 2)
#define IDE_CONTROLLER_IF_SECONDARY_MODE_CAPABILITIES (1 << 3)
#define IDE_CONTROLLER_IF_BUS_MASTER_SUPPORTED        (1 << 7)

#define IDE_CONTROLLER_PCI_CLASS    0x01
#define IDE_CONTROLLER_PCI_SUBCLASS 0x01

#define IDE_CONTROLLER_CHANNEL0_DEFAULT_IO_PORT      0x1F0
#define IDE_CONTROLLER_CHANNEL0_DEFAULT_COMMAND_PORT 0x3F6
#define IDE_CONTROLLER_CHANNEL1_DEFAULT_IO_PORT      0x170
#define IDE_CONTROLLER_CHANNEL1_DEFAULT_COMMAND_PORT 0x376

struct ide_controller {
    struct pci_device pci_device;
};

#endif /* _KERNEL_HAL_X86_64_DRIVERS_IDE_CONTROLLER_H */
