version: "3.9"
services:
  iros:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ..:/build/iros
      - iros-bashhistory:/commandhistory

    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/tmp

    network_mode: host
    privileged: true
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  iros-bashhistory:
