name: Iros Disk Images

on:
    workflow_run:
        workflows: [Toolchain]
        types:
            - completed

jobs:
    build_disk_images:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch: [x86_64]
        container:
            image: ghcr.io/coletrammer/iros_toolchain
            options: --privileged
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Use Ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  key: ${{ github.job }}-${{ matrix.arch }}
            - name: Setup ${{matrix.arch}} Build
              run: IROS_ARCH=${{ matrix.arch }} IROS_CI_BUILD=1 ./scripts/setup.sh
            - name: ${{matrix.arch}} Build
              working-directory: "${{ github.workspace }}/build_${{ matrix.arch }}"
              run: ninja
            - name: Generate ${{ matrix.arch }} Images
              working-directory: "${{ github.workspace }}/build_${{ matrix.arch }}/iros"
              run: ninja image
            - name: Test ${{ matrix.arch }} Images
              working-directory: "${{ github.workspace }}/build_${{ matrix.arch }}/iros"
              run: ctest --rerun-failed --output-on-failure
