export LIBRARY=$(BUILDDIR)/libs/libprocinfo/libprocinfo.a
export OBJS=\
$(BUILDDIR)/libs/libprocinfo/free_procfs_info.o \
$(BUILDDIR)/libs/libprocinfo/read_procfs_global_info.o \
$(BUILDDIR)/libs/libprocinfo/read_procfs_info.o

include ../Makefile.common