OBJS=\
$(BUILDDIR)/userland/nslookup/dns.o \
$(BUILDDIR)/userland/nslookup/main.o \
$(BUILDDIR)/userland/nslookup/mapping.o \
$(BUILDDIR)/userland/nslookup/server.o

EXECUTABLE=$(BUILDDIR)/userland/nslookup/nslookup

include $(ROOT)/userland/Makefile.common