#pragma once

#include <di/meta/list/all.h>
#include <di/meta/list/apply.h>
#include <di/meta/list/as_list.h>
#include <di/meta/list/as_tuple.h>
#include <di/meta/list/bind_back.h>
#include <di/meta/list/bind_front.h>
#include <di/meta/list/cartesian_product.h>
#include <di/meta/list/compose.h>
#include <di/meta/list/concat.h>
#include <di/meta/list/defer.h>
#include <di/meta/list/filter.h>
#include <di/meta/list/fold.h>
#include <di/meta/list/id.h>
#include <di/meta/list/invoke.h>
#include <di/meta/list/is_function_to.h>
#include <di/meta/list/join.h>
#include <di/meta/list/list.h>
#include <di/meta/list/not.h>
#include <di/meta/list/pop_back.h>
#include <di/meta/list/pop_front.h>
#include <di/meta/list/push_back.h>
#include <di/meta/list/push_front.h>
#include <di/meta/list/quote.h>
#include <di/meta/list/repeat.h>
#include <di/meta/list/transform.h>
#include <di/meta/list/type.h>
#include <di/meta/list/uncurry.h>
#include <di/meta/list/unique.h>
#include <di/meta/list/zip.h>
