#pragma once

#include <di/container/concepts/bidirectional_container.h>
#include <di/container/concepts/bidirectional_iterator.h>
#include <di/container/concepts/borrowed_container.h>
#include <di/container/concepts/common_container.h>
#include <di/container/concepts/container.h>
#include <di/container/concepts/container_compatible.h>
#include <di/container/concepts/contiguous_container.h>
#include <di/container/concepts/contiguous_iterator.h>
#include <di/container/concepts/forward_container.h>
#include <di/container/concepts/forward_iterator.h>
#include <di/container/concepts/input_container.h>
#include <di/container/concepts/input_iterator.h>
#include <di/container/concepts/iterator.h>
#include <di/container/concepts/random_access_container.h>
#include <di/container/concepts/random_access_iterator.h>
#include <di/container/concepts/sentinel_for.h>
#include <di/container/concepts/sized_container.h>
#include <di/container/concepts/sized_sentinel_for.h>
#include <di/container/concepts/view.h>
#include <di/container/concepts/viewable_container.h>
