export LIBRARY=$(BUILDDIR)/libs/libgraphics/libgraphics.a
export MAKEFILE=$(ROOT)/libs/libgraphics/Makefile
export OBJS=\
$(BUILDDIR)/libs/libgraphics/pixel_buffer.o \
$(BUILDDIR)/libs/libgraphics/renderer.o

include ../Makefile.common