#ifndef _KERNEL_HAL_X86_DRIVERS_MOUSE_H
#define _KERNEL_HAL_X86_DRIVERS_MOUSE_H 1

#define MOUSE_COMMAND_SINGLE_PACKET 0xEB
#define MOUSE_COMMAND_SET_COMPAQ    0x60
#define MOUSE_COMMAND_GET_COMPAQ    0x20

#endif /* _KERNEL_HAL_X86_DRIVERS_MOUSE_H */
