#ifndef _KERNEL_ARCH_X86_64_IRQS_ARCH_HANDLERS_H
#define _KERNEL_ARCH_X86_64_IRQS_ARCH_HANDLERS_H 1

#include <stdbool.h>

#ifdef KERNEL_USE_PIC
#define EXTERNAL_IRQ_OFFSET 32
#else
#define EXTERNAL_IRQ_OFFSET 48
#endif /* KERNEL_USE_PIC */

#define IRQ_USE_SEPARATE_STACK 1
#define IRQ_USER_AVAILABLE     2
#define IRQ_HAS_ERROR_CODE     4

#define __ENUMERATE_IRQS                                             \
    __ENUMERATE_IRQ(0, 0)                                            \
    __ENUMERATE_IRQ(1, 0)                                            \
    __ENUMERATE_IRQ(2, 0)                                            \
    __ENUMERATE_IRQ(3, 0)                                            \
    __ENUMERATE_IRQ(4, 0)                                            \
    __ENUMERATE_IRQ(5, 0)                                            \
    __ENUMERATE_IRQ(6, 0)                                            \
    __ENUMERATE_IRQ(7, IRQ_HAS_ERROR_CODE)                           \
    __ENUMERATE_IRQ(8, IRQ_USE_SEPARATE_STACK)                       \
    __ENUMERATE_IRQ(9, 0)                                            \
    __ENUMERATE_IRQ(10, IRQ_HAS_ERROR_CODE)                          \
    __ENUMERATE_IRQ(11, IRQ_HAS_ERROR_CODE)                          \
    __ENUMERATE_IRQ(12, IRQ_USE_SEPARATE_STACK | IRQ_HAS_ERROR_CODE) \
    __ENUMERATE_IRQ(13, IRQ_HAS_ERROR_CODE)                          \
    __ENUMERATE_IRQ(14, IRQ_HAS_ERROR_CODE)                          \
    __ENUMERATE_IRQ(15, 0)                                           \
    __ENUMERATE_IRQ(16, 0)                                           \
    __ENUMERATE_IRQ(17, IRQ_HAS_ERROR_CODE)                          \
    __ENUMERATE_IRQ(18, 0)                                           \
    __ENUMERATE_IRQ(19, 0)                                           \
    __ENUMERATE_IRQ(20, 0)                                           \
    __ENUMERATE_IRQ(21, 0)                                           \
    __ENUMERATE_IRQ(22, 0)                                           \
    __ENUMERATE_IRQ(23, 0)                                           \
    __ENUMERATE_IRQ(24, 0)                                           \
    __ENUMERATE_IRQ(25, 0)                                           \
    __ENUMERATE_IRQ(26, 0)                                           \
    __ENUMERATE_IRQ(27, 0)                                           \
    __ENUMERATE_IRQ(28, 0)                                           \
    __ENUMERATE_IRQ(29, 0)                                           \
    __ENUMERATE_IRQ(30, 0)                                           \
    __ENUMERATE_IRQ(31, 0)                                           \
    __ENUMERATE_IRQ(32, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(33, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(34, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(35, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(36, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(37, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(38, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(39, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(40, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(41, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(42, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(43, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(44, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(45, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(46, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(47, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(48, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(49, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(50, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(51, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(52, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(53, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(54, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(55, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(56, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(57, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(58, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(59, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(60, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(61, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(62, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(63, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(64, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(65, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(66, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(67, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(68, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(69, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(70, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(71, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(72, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(73, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(74, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(75, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(76, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(77, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(78, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(79, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(80, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(81, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(82, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(83, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(84, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(85, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(86, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(87, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(88, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(89, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(90, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(91, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(92, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(93, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(94, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(95, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(96, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(97, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(98, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(99, IRQ_USE_SEPARATE_STACK)                      \
    __ENUMERATE_IRQ(100, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(101, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(102, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(103, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(104, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(105, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(106, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(107, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(108, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(109, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(110, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(111, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(112, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(113, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(114, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(115, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(116, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(117, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(118, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(119, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(120, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(121, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(122, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(123, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(124, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(125, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(126, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(127, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(128, IRQ_USER_AVAILABLE)                         \
    __ENUMERATE_IRQ(129, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(130, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(131, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(132, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(133, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(134, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(135, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(136, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(137, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(138, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(139, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(140, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(141, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(142, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(143, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(144, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(145, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(146, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(147, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(148, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(149, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(150, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(151, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(152, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(153, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(154, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(155, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(156, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(157, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(158, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(159, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(160, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(161, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(162, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(163, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(164, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(165, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(166, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(167, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(168, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(169, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(170, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(171, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(172, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(173, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(174, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(175, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(176, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(177, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(178, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(179, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(180, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(181, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(182, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(183, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(184, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(185, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(186, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(187, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(188, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(189, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(190, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(191, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(192, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(193, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(194, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(195, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(196, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(197, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(198, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(199, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(200, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(201, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(202, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(203, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(204, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(205, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(206, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(207, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(208, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(209, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(210, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(211, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(212, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(213, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(214, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(215, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(216, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(217, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(218, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(219, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(220, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(221, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(222, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(223, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(224, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(225, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(226, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(227, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(228, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(229, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(230, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(231, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(232, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(233, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(234, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(235, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(236, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(237, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(238, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(239, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(240, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(241, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(242, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(243, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(244, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(245, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(246, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(247, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(248, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(249, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(250, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(251, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(252, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(253, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(254, IRQ_USE_SEPARATE_STACK)                     \
    __ENUMERATE_IRQ(255, IRQ_USE_SEPARATE_STACK)

#undef __ENUMERATE_IRQ
#define __ENUMERATE_IRQ(n, f) void interrupt_handler_##n(void);
__ENUMERATE_IRQS

static inline bool irq_is_external(int n) {
    return n >= 32 && n != 128;
}

#endif /* _KERNEL_ARCH_X86_64_IRQS_ARCH_HANDLERS_H */
