name: Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Prune tags for closed PRs
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.PRIVATE_ADMIN_GITHUB_TOKEN }}
          container: iros_toolchain
          prune-tags-regexes: |
            ^pr-${{ github.event.number }}$
      - name: Prune old untagged images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          user: ${{ github.actor }}
          token: ${{ secrets.PRIVATE_ADMIN_GITHUB_TOKEN }}
          container: iros_toolchain
          prune-untagged: true
