name: Lint

on:
  push:
    branches: [iris]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  CLANG_FORMAT_MATCH: '\.(cpp|h)$'
  PRETTIER_MATCH: '(\.prettierrc|\.clangd|\.clang-tidy|\.clang-format|\.(json|code-snippets|md|yml))$'
  CMAKE_FORMAT_MATCH: '(CMakeLists.txt|CMakeToolchain.*.txt|\.cmake)$'

jobs:
  lint:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting and linting
        run: |
          nix flake check
