name: Linux CI

on:
    push:
        branches: [iris]
    pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
    cancel-in-progress: true

jobs:
    linux_build_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                preset: [ubasan, dius_runtime_release, coverage]
        steps:
            - run: |
                  sudo apt-get -y update && sudo apt-get -y install gcc-12 g++-12 gcovr
                  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 --slave /usr/bin/g++ g++ /usr/bin/g++-12 --slave /usr/bin/gcov gcov /usr/bin/gcov-12
                  sudo update-alternatives --set gcc /usr/bin/gcc-12
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Get latest CMake and Ninja
              uses: lukka/get-cmake@latest
              with:
                  cmakeVersion: latest
                  ninjaVersion: latest
            - name: Get and cache ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  key: ${{ github.job }}-${{ matrix.preset }}
            - name: Build and test
              uses: lukka/run-cmake@v10
              with:
                  configurePreset: ${{ matrix.preset }}
                  buildPreset: ${{ matrix.preset }}
                  testPreset: ${{ matrix.preset }}
            - name: Collect code coverage information
              run: |
                  gcovr -j ${{env.nproc}} --delete --root . --print-summary --xml-pretty --xml coverage.xml build/native/coverage
              if: matrix.preset == 'coverage'
            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                  flags: ${{ runner.os }}
                  name: ${{ runner.os }}-coverage
                  files: ./coverage.xml
              if: matrix.preset == 'coverage'
