name: Native Tests

on:
    push:
        branches:
            - "master"

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                arch: [x86_64]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                  sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
                  sudo apt update -y
                  sudo apt install -y ccache cmake ninja-build gcc-11 g++-11 libstdc++-11-dev
            - name: Use Ccache
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                  key: ${{ github.job }}-${{ matrix.arch }}
            - name: Configure for native ${{ matrix.arch }}
              run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11
            - name: Build for native ${{ matrix.arch }}
              run: cmake --build build
            - name: Test for native ${{ matrix.arch }}
              working-directory: ${{ github.workspace }}/build
              run: ctest --rerun-failed --output-on-failure
