name: Build Toolchain

on:
    push:
        branches:
            - "master"
        paths:
            - 'Dockerfile'
            - 'toolchain/**'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push toolchain image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: ghcr.io/coletrammer/iros_toolchain:latest
